name: 'Build engine'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'gamedata/**'
      - 'sdk/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - '**/*.ltx'
      - '**/*.json'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'gamedata/**'
      - 'sdk/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - '**/*.ltx'
      - '**/*.json'

defaults:
  run:
    shell: pwsh

jobs:
  build-engine:
    name: 'Build engine'

    strategy:
      matrix:
        system:
          - windows-2022
        preset:
          - Engine
        platform:
          - x86
          - x64
        config:
          - Debug
          - RelWithDebInfo
          - Release

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ matrix.preset }}-NuGet-
          restore-keys: |
            ${{ matrix.preset }}-NuGet-
          path: |
            ~/.nuget/packages

      - name: Configure engine
        run: |
          cmake --preset ${{ matrix.preset }}-${{ matrix.platform }}

      - name: Build engine
        run: |
          cmake --build --preset ${{ matrix.preset }}-${{ matrix.platform }}-${{ matrix.config }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: engine-binaries-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/*.exe
            build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/*.dll

      - name: Upload symbols
        uses: actions/upload-artifact@v4
        if: ${{ matrix.config != 'Release' }}
        with:
          name: engine-symbols-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/*.pdb

      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: engine-libraries-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/lib/${{ matrix.config }}/

      - name: Upload packages
        uses: actions/upload-artifact@v4
        if: ${{ (matrix.config == 'Debug' && matrix.platform == 'x64') }}
        with:
          name: engine-packages-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/packages/

  build-compressor:
    name: 'Build compressor'

    strategy:
      matrix:
        system:
          - windows-2022
        preset:
          - Compressor
        platform:
          - x86
          - x64
        config:
          - Debug
          - RelWithDebInfo
          - Release

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure compressor
        run: |
          cmake --preset ${{ matrix.preset }}-${{ matrix.platform }}

      - name: Build compressor
        run: |
          cmake --build --preset ${{ matrix.preset }}-${{ matrix.platform }}-${{ matrix.config }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: compressor-binaries-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/*.exe
            build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/*.dll

      - name: Upload symbols
        uses: actions/upload-artifact@v4
        if: ${{ matrix.config != 'Release' }}
        with:
          name: compressor-symbols-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/*.pdb

      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: compressor-libraries-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/lib/${{ matrix.config }}/

  pack-assets:
    name: 'Pack assets'

    needs: build-compressor

    strategy:
      matrix:
        system:
          - windows-2022
        preset:
          - Compressor
        platform:
          - x64
        config:
          - Release

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get compressor
        uses: actions/download-artifact@v4
        with:
          name: compressor-binaries-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/

      - name: Generate patch
        run: |
          ${{ github.workspace }}/generate-patch.bat
          type *.log
          move ${{ github.workspace }}/gamedata ${{ github.workspace }}/gamedata_full
          move ${{ github.workspace }}/patch ${{ github.workspace }}/gamedata

      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: compressor-assets-${{ github.sha }}
          path: |
            gamedata/
            patches/xpatch_03.db
            fsgame.ltx

  publish-engine:
    name: 'Publish engine'

    needs:
      - build-engine
      - pack-assets

    strategy:
      matrix:
        system:
          - windows-2022
        platform:
          - x64

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get engine (x86)
        uses: actions/download-artifact@v4
        with:
          name: engine-binaries-x86-Release-${{ github.sha }}
          path: build/x86/Engine/bin/Release/

      - name: Get engine (x64)
        uses: actions/download-artifact@v4
        with:
          name: engine-binaries-x64-Release-${{ github.sha }}
          path: build/x64/Engine/bin/Release/

      - name: Get assets
        uses: actions/download-artifact@v4
        with:
          name: compressor-assets-${{ github.sha }}
          path: ./

      - name: Upload engine
        uses: actions/upload-artifact@v4
        with:
          name: engine-publish-${{ github.sha }}
          path: |
            build/
            gamedata/
            patches/xpatch_03.db
            fsgame.ltx
