name: 'Build utilities'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'gamedata/**'
      - 'sdk/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - '**/*.ltx'
      - '**/*.json'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'gamedata/**'
      - 'sdk/**'
      - 'src/**'
      - '**/CMakeLists.txt'
      - '**/*.ltx'
      - '**/*.json'

defaults:
  run:
    shell: pwsh

jobs:
  build-utilities:
    name: 'Build utilities'

    strategy:
      matrix:
        system:
          - windows-2022
        preset:
          - Utilities
        platform:
          - x86
          - x64
        config:
          - Debug
          - RelWithDebInfo
          - Release

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ matrix.preset }}-NuGet-
          restore-keys: |
            ${{ matrix.preset }}-NuGet-
          path: |
            ~/.nuget/packages

      - name: Configure utilities
        run: |
          cmake --preset ${{ matrix.preset }}-${{ matrix.platform }}

      - name: Build utilities
        run: |
          cmake --build --preset ${{ matrix.preset }}-${{ matrix.platform }}-${{ matrix.config }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: utilities-binaries-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/*.exe
            build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/*.dll

      - name: Upload symbols
        uses: actions/upload-artifact@v4
        if: ${{ matrix.config != 'Release' }}
        with:
          name: utilities-symbols-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/bin/${{ matrix.config }}/*.pdb

      - name: Upload libraries
        uses: actions/upload-artifact@v4
        with:
          name: utilities-libraries-${{ matrix.platform }}-${{ matrix.config }}-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/lib/${{ matrix.config }}/

      - name: Upload packages
        uses: actions/upload-artifact@v4
        if: ${{ (matrix.config == 'Debug' && matrix.platform == 'x64') }}
        with:
          name: utilities-packages-${{ github.sha }}
          path: |
            build/${{ matrix.platform }}/${{ matrix.preset }}/packages/
