name: Building

on: [ push, pull_request ]

jobs:
  build:
    name: 'Building'
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [ Debug, Mixed, Release, Debug_Dedicated, Mixed_Dedicated, Release_Dedicated ]
        platform: [ x86 ]

    env:
      solution_name: XRay.Engine.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cancel previous runs
      uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get dependencies
      run: |
        curl https://github.com/ixray-team/ixray-1.6-stcop/releases/download/r0.2/sdk-directxsdk-mar2009.7z -O directxsdk-mar2009.7z
        7z x directxsdk-mar2009.7z
        curl https://github.com/ixray-team/ixray-1.6-stcop/releases/download/r0.2/sdk-directxsdk-jun2010.7z -O directxsdk-jun2010.7z
        7z x directxsdk-jun2010.7z
        git clone --branch Release_3.1.0 --depth 1 https://github.com/dockpanelsuite/dockpanelsuite.git dep/dockpanelsuite
      shell: powershell

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Cache packages
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget

    - name: Restore solution
      run: |
        nuget restore $env:solution_name

    - name: Build solution
      run: |
        msbuild $env:solution_name -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} -m -nologo

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: bin (${{ matrix.configuration }})
        path: bin/

    - name: Upload libraries
      uses: actions/upload-artifact@v3
      with:
        name: lib (${{ matrix.configuration }})
        path: lib/

    - name: Upload gamedata
      uses: actions/upload-artifact@v3
      with:
        name: gamedata
        path: gamedata/
