name: Building

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Mixed, Release]
        platform: [Win32]

    env:
      solution_name: XRay.Engine.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get dependencies
      run: |
        curl https://github.com/ixray-team/ixray-1.6-stcop/releases/download/r0.2/sdk-directxsdk-mar2009.7z -O directxsdk-mar2009.7z
        7z x directxsdk-mar2009.7z
        curl https://github.com/ixray-team/ixray-1.6-stcop/releases/download/r0.2/sdk-directxsdk-jun2010.7z -O directxsdk-jun2010.7z
        7z x directxsdk-jun2010.7z
        git clone --branch aug2021 --depth 1 https://github.com/microsoft/DirectXTex.git dep/DirectXTex
        git clone --branch Release_3.1.0 --depth 1 https://github.com/dockpanelsuite/dockpanelsuite.git dep/dockpanelsuite
      shell: powershell

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build solution
      run: |
        msbuild $env:solution_name -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} -r -m -nologo

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: out ${{ matrix.configuration }}
        path: |
          bin/
          lib/
