name: 'Build engine'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'proj/**'
      - 'sdk/**'
      - 'src/**'
      - '*.sln'
      - '*.props'
      - '*.targets'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'proj/**'
      - 'sdk/**'
      - 'src/**'
      - '*.sln'
      - '*.props'
      - '*.targets'

defaults:
  run:
    shell: pwsh

jobs:
  build-engine:
    name: 'Building'

    strategy:
      matrix:
        system:
          - windows-2022
        config:
          - Debug
          - Mixed
          - Release
          - Debug_Dedicated
          - Mixed_Dedicated
          - Release_Dedicated
        platform:
          - Win32

    runs-on: ${{ matrix.system }}

    env:
      solution_name: XRay.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: |
          ${{ github.workspace }}\get-dependencies.bat

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build solution
        run: |
          msbuild $env:solution_name `
            -p:Configuration=${{ matrix.config }} `
            -p:Platform=${{ matrix.platform }} `
            -restore `
            -maxCpuCount `
            -nologo

      - name: Cleanup
        run: |
          ${{ github.workspace }}/delete-symbols.bat

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin (${{ matrix.config }}) ${{ github.sha }}
          path: bin/

      - name: Upload libraries
        uses: actions/upload-artifact@v3
        with:
          name: lib (${{ matrix.config }}) ${{ github.sha }}
          path: lib/

      - name: Upload gamedata
        uses: actions/upload-artifact@v3
        with:
          name: gamedata ${{ github.sha }}
          path: gamedata/

  pack-assets:
    name: 'Packing'

    #needs: build-engine

    strategy:
      matrix:
        system:
          - windows-2022
        config:
          - Release
        platform:
          - Win32

    runs-on: ${{ matrix.system }}

    env:
      compressor: src\utils\xrCompress\xrCompress.vcxproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build compressor
        run: |
          msbuild $env:compressor `
            -p:Configuration=${{ matrix.config }} `
            -p:Platform=${{ matrix.platform }} `
            -p:SolutionDir=${{ github.workspace }} `
            -nologo

      - name: Check binaries
        run: |
          ls bin

      - name: Get original assets
        run: |
          git clone `
            --branch r0.3 `
            --depth 1 `
            ${{ github.server_url }}/${{ github.repository }} `
            ${{ github.workspace }}/temp/r0.3
          move ${{ github.workspace }}/temp/r0.3/gamedata `
            ${{ github.workspace }}/gamedata_origin

      - name: Generate patch
        run: |
          ${{ github.workspace }}/bin/xrCompress `
            -diff gamedata gamedata_origin
            -out patch

      - name: Pack patch
        run: |
          ${{ github.workspace }}/bin/xrCompress patch `
            -ltx datapack.ltx
          move patch.pack_#0 xpatch_03.db
          cat engine.log

      - name: Upload patch
        uses: actions/upload-artifact@v3
        with:
          name: xpatch_03 ${{ github.sha }}
          path: xpatch_03.db
